name: funica
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  image_picker: ^1.0.7
  permission_handler: ^11.3.0
  bottom_picker: 
  country_code_picker: 
  country_pickers: ^3.0.1
  dropdown_button2: 
  gradient_borders: 
  flutter_slidable: 
  gap: ^3.0.1 
  modal_bottom_sheet: ^3.0.0
  easy_stepper: 
  flutter_staggered_grid_view:
  table_calendar: 
  syncfusion_flutter_sliders:
  svg_flutter: 
  google_fonts: 
  get: 
  simple_gradient_text: 
  weekly_date_picker:
  cached_network_image: 
  intl:
  carousel_slider: 
  pinput: 
  bottom_navy_bar: 
  stylish_bottom_bar: 
  cupertino_icons: 
  flutter_animate: ^4.5.2
  shared_preferences: 
  bounce: ^1.0.2
  intro_screen_onboarding_flutter: ^1.0.0
  smooth_page_indicator: 
  syncfusion_flutter_charts: ^28.1.4
  fl_chart: ^0.68.0           
  flutter_advanced_drawer: 
  tap_to_expand: ^0.7.2
  persistent_bottom_nav_bar_v2: 
  dotted_border:
  flutter_spinkit: ^5.2.0
  action_slider: ^0.7.0
  animated_bottom_navigation_bar: ^1.4.0
  internet_connection_checker: ^3.0.1
  flutter_localizations:
    sdk: flutter
  connectivity_plus: ^6.1.5
  fluttertoast: ^8.2.12
  sizer: ^3.1.3
  country_picker: ^2.0.0
  get_storage: ^2.1.1
  shimmer: ^3.0.0
  


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/


  fonts:
    - family: Figtree
      fonts:
        - asset: assets/fonts/FigtreeLight.ttf
          weight: 300 
        - asset: assets/fonts/FigtreeRegular.ttf
          weight: 400      
        - asset: assets/fonts/FigtreeMedium.ttf
          weight: 500  
        - asset: assets/fonts/FigtreeSemiBold.ttf
          weight: 600    
        - asset: assets/fonts/FigtreeBold.ttf
          weight: 700     
        - asset: assets/fonts/FigtreeExtraBold.ttf
          weight: 800    
        - asset: assets/fonts/FigtreeBlack.ttf
          weight: 900    

flutter_assets:
  assets_path: assets/
  output_path: lib/generated/
  filename: assets.dart
  field_prefix: ""